apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.db_name }}-${{ values.db_type_short }}-vm   # matches KubeVirt VM name exactly
  description: "${{ values.db_type }} database VM"
  annotations:
    dbaas/connection-url: "${{ values.db_standard_url }}"
spec:
  type: database
  owner: ${{ values.owner }}
  lifecycle: production
