apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: askjalskdasdasdasdas
  title: aslkasjdkljalsdkjasd
  description: Automatically provision a dedicated PostgreSQL or MySQL database VM on OpenShift Virtualization via AAP.
  namespace: default
  tags:
    - database
    - openshift
    - dbaas
spec:
  owner: RedHat
  type: service
  
  parameters:
    - title: Provide Details
      properties: {}
      
  steps:
    - id: launch-demo-job
      name: Triggering Hello World Playbook on AAP...
      action: rhaap:launch-job-template
      input:
        token: ${{ secrets.aapToken }}
        values:
          template: "hello-world"
          extraVariables:
             kajshkjahs: kaskjads
        
  output:
    text:
      - title: Debug
        content: |
          ${{ steps['launch-demo-job'].output | json }}
    links:
      - title: View in RH AAP
        url: ${{ steps['launch-demo-job'].output.data.url }}
