apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: New Input form
  title: New Input form Testing
  description: Create a new Form Testing
  tags:
    - recommended
    - ansible
    - testing
    - playbook
spec:
  owner: ansible-authors
  system: ansible
  type: service
  parameters:
    - title: Provide information about the new component
      required:
        - repoOwner
        - repoName
        - owner
        - collectionGroup
        - collectionName
      properties:
        sourceControl:
          title: Select source control option
          type: string
          description: Select the source control option for your Ansible project.
          default: github.com
          enum:
            - github.com
          enumNames:
            - 'GitHub'
        repoOwner:
          title: Source code repository organization name or username
          type: string
          description: The organization name or username of your source code repository. For example, “my-github-username”.
          maxLength: 100
        repoName:
          title: Playbook repository name
          description: The name of the new playbook project repository. For example, “my-new-playbook-repo”.
          type: string
          maxLength: 100
          pattern: '^([a-zA-Z][a-zA-Z0-9_]*)(-[a-zA-Z0-9_]+)*$'
        description:
          title: Playbook description
          type: string
          description: Describe the playbook and its purpose to help other users understand what to use it for.
          maxLength: 350
        collectionGroup:
          title: Playbook project's collection namespace
          description: The collection namespace in your new playbook repository. For example, “my_new_collection_namespace”.
          type: string
          maxLength: 63
          minLength: 2
          pattern: '^[a-z][a-z0-9_]+$'
        collectionName:
          title: Playbook project's collection name
          description: The collection name in your new playbook repository. For example, “my_new_collection_name”.
          type: string
          maxLength: 63
          minLength: 2
          pattern: '^[a-z][a-z0-9_]+$'
        owner:
          title: Catalog Owner name
          type: string
          description: The Red Hat Developer Hub catalog item owner. This will appear on the “My items” tab. For example, “my-devhub-username”.
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
                - User
        system:
          title: System
          type: string
          description: The Red Hat Developer Hub system catalog item name. This will appear on the “My items” tab. For example, “my-devhub-system”.
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - System
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}

      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
